### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by taatu** [iabarca/lawena-recording-tool#28]
My lawena seems to not be able to launch tf2, restarting the computer etc did not help and I haven't messed with any settings since downloading. here is a log of the latest session.

[18-01-2014 13:58:42.593] Lawena Recording Tool 4.0.10 build 20131019193756
[18-01-2014 13:58:42.593] TF2 path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf
[18-01-2014 13:58:42.594] Movie path: C:\Users****_\Desktop\vids\precs
[18-01-2014 13:58:42.594] Lawena path: C:\Users\**_**\Desktop\tf2modd\lawena stuf\lawena.
[18-01-2014 13:58:44.803] Skybox loading and preview generation complete
[18-01-2014 13:58:47.128] [handle] No matching handles found.
[18-01-2014 13:58:47.844] [handle] No matching handles found.
[18-01-2014 13:58:47.848] Settings saved
[18-01-2014 13:58:47.853] Making a backup of your config files
[18-01-2014 13:58:47.973] Making a backup of your custom files
[18-01-2014 13:58:47.981] Copying selected hud files
[18-01-2014 13:58:48.102] Copying selected custom vpks and folders
[18-01-2014 13:58:48.102] Copying custom VPK: custom\default_cfgs.vpk
[18-01-2014 13:58:48.104] Copying custom VPK: custom\no_announcer_voices.vpk
[18-01-2014 13:58:48.106] Copying custom VPK: custom\no_applause_sounds.vpk
[18-01-2014 13:58:48.107] Copying custom VPK: custom\no_domination_sounds.vpk
[18-01-2014 13:58:48.163] No enhanced particles were selected
[18-01-2014 13:58:48.163] Starting TF2 in 1920x1080 with dxlevel 98
[18-01-2014 13:58:48.184] TF2 console output saved to: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\console.log
[18-01-2014 13:58:48.191] Process was interrupted
java.io.IOException: Cannot run program "98/steam.exe": CreateProcess error=2, Määritettyä tiedostoa ei löydy
    at java.lang.ProcessBuilder.start(Unknown Source)
    at lwrt.CommandLine.startTf(CommandLine.java:277)
    at lwrt.Lawena$StartTfTask.doInBackground(Lawena.java:235)
    at lwrt.Lawena$StartTfTask.doInBackground(Lawena.java:175)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, Määritettyä tiedostoa ei löydy
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 10 more
[18-01-2014 13:58:48.194] TF2 launch timeout: around 120 seconds
[18-01-2014 14:00:53.883] TF2 launch timed out after 120 seconds
[18-01-2014 14:00:53.919] Restoring all your config files
[18-01-2014 14:00:53.964] Restoring all your custom files
[18-01-2014 14:01:01.748] Settings saved

**Comment by iabarca** [comment]
This is veery old but a few weeks ago I understood this issue due to the help of another guy with the same issue and it's related to the registry not holding the correct value for the SteamPath, or holding it in a way that's not readable properly by Lawena.

Lawena now has a way to specify a custom Steam path working around this issue.

**Comment by kayenkayen** [comment]
Could you explain the exact workaround for the SteamPath? I can't find it anywhere. My Steam folder is in D: rather than C: (partitioned harddrive) and I believe that may be what's causing me this problem.

**Comment by iabarca** [comment]
- Open the ``settings.lwf`` file with notepad or similar editor
- Find the line that starts with ``SteamDir=``
- Append your actual Steam directory (the one that contains steam.exe file) to that line. Backslashes should be entered as ``\\``
- Save and relaunch the tool

Let me know if it works.

**Comment by kayenkayen** [comment]
Thanks for the quick reply! But it hasn't worked, I get this in the logs. It also seems to rewrite the settings.lwf so that the line reads the default "SteamDir=c\:\\program files (x86)\\steam" instead of "SteamDir=d\:\\program files\\steam" like attempted.

[16:45:03] Process was interrupted: java.io.IOException: Cannot run program "c:\program files (x86)\steam/steam.exe": CreateProcess error=2, The system cannot find the file specified
[16:45:03] TF2 launch timeout: around 30 seconds
[16:45:36] TF2 launch timed out after 30 seconds
[16:45:36] Restoring all your custom files
[16:45:37] Restoring all your config files
[16:45:37] Backup folders size: 1.9 MB
[16:45:37] Creating a backup of your files in: D:\Program Files\Steam\SteamApps\common\Team Fortress 2\tf\lawena-user.150312164537.bak.zip
[16:45:37] Restoring: Deleting files inside lwrtcustom
[16:45:37] Restoring: Deleting files inside lwrtcfg
[16:45:37] *** Restore and cleanup completed
[16:45:37] Deleted last backup: D:\Program Files\Steam\SteamApps\common\Team Fortress 2\tf\lawena-user.150312164537.bak.zip

**Comment by iabarca** [comment]
That's because your registry has an invalid value for SteamPath as opposed to having no value saved.

I'll push a fix to work around that in a few minutes. You can also reinstall Steam or go to registry key SteamPath in HKEY_CURRENT_USER\\Software\\Valve\\Steam.

**Comment by iabarca** [comment]
Ok the fix is live in the preview branch. In case you are not already in that branch follow these steps:

1. Go to Help -> About menu item.
2. Press "Select Updater Branch..."
3. Select "preview-v4.1" and press OK
4. Restart Lawena

Version should read **4.1.6-4** at the top of the window. Thanks for reporting the problem

**Comment by kayenkayen** [comment]
You're amazing! Thank you.

**Comment by iabarca** [comment]
You're welcome, feel free to create a new issue or join the chat at [gitter](https://gitter.im/iabarca/lawena-recording-tool) in case you have problems.
